############## style ##############
style:
  layout:
    max-width: "1125px" #最大宽度
  color:
    theme-main: "#1A98FF" # 主色调
    theme-secondary: "#DDF0FF" # 次色调
    text-main: "#333333" # 文字主色调
    text-secondary: "#898FA0" # 文字次色调


########## 关于主页的设置 ##########
# icon
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/NewTux.svg/1000px-NewTux.svg.png #标签页图标
#  header
site_name: Sorry My World.

menu:
  HOME: /
  BLOG: /archives
  TIME: http://p.timepill.net/
  MOOD: /essay
  TRAVELLINGS: https://travellings.now.sh/

## 本地搜索
search:
  open: true # 是否开启
  page: /search # 在上面页面上（通常命名为search）
  


# 自我介绍
intro:
  title: Hi.I'm Yangyang.
  sub: '[Operation and Maintenance Engineer]()' # markdown语法
  avator: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/NewTux.svg/1000px-NewTux.svg.png #头像 暂时还没用到
  author: Yangyang #所有文章的默认作者

#联系方式  
#更多图标：https://remixicon.com/
contact:
  Music:
    - https://music.163.com/#/discover/toplist?id=19723756
    - ri-disc-line
  Bilibili:
    - https://www.bilibili.com/?spm_id_from=333.337.b_696e7465726e6174696f6e616c486561646572.1
    - ri-bilibili-line
  Email:
    - mailto:1771566679@qq.com
    - ri-mail-line
  GitHub:
    - https://github.com/Linux-yangyang
    - ri-github-line
  CSDN:
    - https://blog.csdn.net/yy150122
    - ri-pen-nib-line



########## 关于文章的设置 ##########

# 文章toc索引栏设置
toc:
  max: 2 #最大
  min: 2 #最小

# 插件
plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/github.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

# 评论系统设置
comments:
  valine:
    open: true # true | false 是否打开
    appid: VGzYQ2vUvXBqHjPejmlg5YiB-gzGzoHsz #Leancloud应用的AppID  这里和下面的要换成你自己的啊QAQ
    appkey: DP7BuydUbzdbzwBC11Rcp5N6 #Leancloud应用的AppKey
    verify: false #验证码
    notify: true #评论回复提醒
    avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    #头像类型可见： https://valine.js.org/avatar.html
    placeholder: 留下你来过的痕迹~ #评论框占位符
  gitalk:
    open: false # true | false 是否打开
    owner: Linux-yangyang  #Github 用户名,
    repo: blog-gitalk #储存评论issue的github仓库名
    admin: Linux-yangyang #Github 用户名
    clientID: 1fcfa2974e7aa23cf199 #`Github Application clientID`
    clientSecret: 3f31281ae565a00ab6e3e4adeee7a4ceaeb48e06 #`Github Application clientSecret`
  
snow: true


############## 其他 ##############

# 页脚
footer: The door to the new world [DOOR](ftp://yangyang.host/) # markdown语法
